excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ricoramiro.github.io
title: Learning to Become a Web Developer 
tagline: Blogging for Experience
description: I'm a web dev student that has some experience.  I programmed Apple computers in the late or mid eighties
and I currently know html 5 and I'm learning CSS.
paginate: 5